--1)
SELECT * FROM JOB;
-- 대리의 직급 코드는 J6
SELECT EMP_ID 사번 , EMP_NAME 사원명, PHONE 연락처, EMAIL 이메일 FROM EMPLOYEE WHERE EMP_NAME NOT LIKE '김%' AND JOB_CODE = 'J6';

--2)
SELECT EMP_NAME, SALARY, DEPT_CODE, JOB_CODE FROM EMPLOYEE WHERE ENT_YN = 'N' ORDER BY DEPT_CODE, JOB_CODE DESC;

--3)
SELECT * FROM DEPARTMENT;
-- 마케팅부의 부서코드는 D3 , 국내영업부의 부서코드는 D4
SELECT * FROM EMPLOYEE;
SELECT EMP_NAME, EMP_NO, SALARY, HIRE_DATE FROM EMPLOYEE WHERE DEPT_CODE IN ('D3' , 'D4') ORDER BY SUBSTR(EMP_NO, 1, 2); 
-- D3, D4에 속한 사람이 없음

--4)
SELECT EMP_NAME, HIRE_DATE, ENT_DATE FROM EMPLOYEE WHERE ENT_DATE IS NOT NULL;

--5)
SELECT * FROM JOB;
SELECT * FROM DEPARTMENT;
--해외영업1부는 D5
SELECT EMP_NAME, EMP_ID, PHONE, SALARY FROM EMPLOYEE WHERE JOB_CODE NOT IN('J7') AND DEPT_CODE IN ('D5') ORDER BY SALARY;

--6)
SELECT INSTR(PHONE, 2230) FROM EMPLOYEE;
SELECT EMP_ID, PHONE , EMP_NAME FROM EMPLOYEE WHERE PHONE LIKE ('%2230%') AND HIRE_DATE = '16/11/28';

--7)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY FROM EMPLOYEE WHERE SALARY >= 4000000 AND BONUS IS NOT NULL ORDER BY SALARY;

--8)
SELECT * FROM JOB;
-- 대리는 J6
SELECT EMP_NAME, PHONE FROM EMPLOYEE WHERE EMP_NO LIKE '%-1%' AND JOB_CODE = 'J6';

--9)
SELECT * FROM DEPARTMENT;
--기술지원부는 D8
SELECT * FROM EMPLOYEE WHERE SALARY > 2200000 AND DEPT_CODE = 'D8' ORDER BY SALARY DESC;

--10)
SELECT * FROM EMPLOYEE;
SELECT * FROM NATIONAL;
SELECT * FROM LOCATION;
SELECT * FROM DEPARTMENT;
--한국은 KO, L1
SELECT DISTINCT EMP_NAME, DEPT_CODE, HIRE_DATE  FROM EMPLOYEE A , DEPARTMENT B WHERE B.location_id = 'L1' AND SUBSTR(A.HIRE_DATE, 1, 2) LIKE '9%';
--select * from employee WHERE HIRE_DATE < '00/01/01';
--11)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE FROM EMPLOYEE WHERE SUBSTR(HIRE_DATE,1,2) > 20 ORDER BY EMP_NAME;

--12)
SELECT * FROM JOB;
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;
-- D5, D6, D7
-- 대리와 부장은 J6, J3
SELECT EMP_NAME, EMP_ID, JOB_CODE, DEPT_CODE, EMAIL, PHONE FROM EMPLOYEE WHERE JOB_CODE IN ('J6','J3') AND DEPT_CODE IN ('D5','D6','D7')
ORDER BY JOB_CODE DESC, DEPT_CODE DESC;

--13)
SELECT * FROM JOB;
--J5, J6, J7
SELECT * FROM EMPLOYEE WHERE JOB_CODE IN ('J5', 'J6','J7') ORDER BY SALARY;

--14)
SELECT EMP_ID, EMP_NAME, PHONE, SALARY, (SALARY * (1+NVL(BONUS,0))) * 12 연봉
FROM EMPLOYEE
WHERE PHONE LIKE '0103%' AND SALARY >= 3000000;

--15)
SELECT EMP_ID, EMP_NAME , SALARY, PHONE FROM EMPLOYEE WHERE EMP_NAME LIKE '김%' AND SALARY BETWEEN 2000000 AND 2500000;

