CREATE TABLE EMPL(
    EID CHAR(3) ,
    ENAME VARCHAR2(20),
    ENO CHAR(14), 
    EMAIL VARCHAR2(25), 
    PHONE VARCHAR2(12),
    HIRE_DATE DATE DEFAULT SYSDATE,
    JID CHAR(2) ,
    SALARY NUMBER ,
    BONUS_PCT NUMBER ,
    MARRIAGE CHAR(1) DEFAULT 'N',
    MID CHAR(3) ,
    DID CHAR(2) ,
    CONSTRAINT PKEID PRIMARY KEY(EID),
    CONSTRAINT NENAME CHECK(ENAME IS NOT NULL),
    CONSTRAINT UENO UNIQUE(ENO),
    CONSTRAINT NENO CHECK(ENO IS NOT NULL),
    CONSTRAINT EMAIL UNIQUE(EMAIL),
    CONSTRAINT FKJID FOREIGN KEY(JID) REFERENCES JOB(JOB_CODE) ON DELETE SET NULL,
    CONSTRAINT CHK CHECK(MARRIAGE IN ('Y', 'N')),
    CONSTRAINT FKMID FOREIGN KEY(MID) REFERENCES EMPL(EID) ON DELETE SET NULL,
    CONSTRAINT FKDID FOREIGN KEY(DID) REFERENCES DEPARTMENT ON DELETE CASCADE
);

DROP TABLE EMPL;

COMMENT ON COLUMN EMPL.EID IS '사번';
COMMENT ON COLUMN EMPL.ENAME IS '사원명';
COMMENT ON COLUMN EMPL.ENO IS '주민번호';
COMMENT ON COLUMN EMPL.EMAIL IS '이메일';
COMMENT ON COLUMN EMPL.PHONE IS '전화번호';
COMMENT ON COLUMN EMPL.HIRE_DATE IS '입사일';
COMMENT ON COLUMN EMPL.JID IS '직급번호';
COMMENT ON COLUMN EMPL.SALARY IS '급여';
COMMENT ON COLUMN EMPL.BONUS_PCT IS '보너스포인트';
COMMENT ON COLUMN EMPL.MARRIAGE IS '결혼여부';
COMMENT ON COLUMN EMPL.MID IS '관리자사번';
COMMENT ON COLUMN EMPL.DID IS '부서번호';




CREATE TABLE DEPARTMENT2(

DEPTNO NUMBER PRIMARY KEY,

DEPTNAME NVARCHAR2(10) NOT NULL

);

CREATE TABLE EMPLOYEE2(

EMPNO NUMBER PRIMARY KEY,

EMPNAME NVARCHAR2(10) NOT NULL,

DEPTNO NUMBER REFERENCES DEPARTMENT2(DEPTNO)

);

SELECT EMPNO, EMPNAME, E.DEPTNO, DEPTNAME
FROM EMPLOYEE2 E, DEPARTMENT2 D
WHERE E.DEPTNO = D.DEPTNO;

SELECT EMPNO, EMPNAME, EMPLOYEE2.DEPTNO, DEPTNAME 
FROM EMPLOYEE2, DEPARTMENT2
WHERE EMPLOYEE2.DEPTNO = DEPARTMENT2.DEPTNO;


CREATE TABLE PRODUCT(
    PNAME VARCHAR2(20),
    PRICE NUMBER,
    PSTATE CHAR(1),
    PCOMMENT VARCHAR2(100)
);

INSERT INTO PRODUCT 
VALUES('갤럭시노트10',1950000, 'A', '사전예약 시행중');

INSERT INTO PRODUCT 
VALUES('MACBOOK AIR',1500000, 'B', '맥북 프로보다 가볍게 사용할 수 있음');

INSERT INTO PRODUCT 
VALUES('LG V7',780000, 'C', '카메라 성능이 세계적으로 우수함');

SELECT * FROM PRODUCT;



