CREATE TABLE TB_DEPARTMENT(
    DEPARTMENT_NO VARCHAR2(20) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL,
    CATEGORY VARCHAR2(20) NULL,
    OPEN_YN CHAR(1) NULL,
    CAPACITY NUMBER NULL,
    CONSTRAINT DEPARTMENT_NO_PK PRIMARY KEY(DEPARTMENT_NO)
);

COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NAME IS '학과 이름';
COMMENT ON COLUMN TB_DEPARTMENT.CATEGORY IS '계열';
COMMENT ON COLUMN TB_DEPARTMENT.OPEN_YN IS '개설 여부';
COMMENT ON COLUMN TB_DEPARTMENT.CAPACITY IS '정원';

INSERT INTO TB_DEPARTMENT 
VALUES('001','국어국문학과','인문사회','Y',20);
INSERT INTO TB_DEPARTMENT 
VALUES('002','영어영문학과','인문사회','Y',36);
INSERT INTO TB_DEPARTMENT 
VALUES('003','사학과','인문사회','Y',28);
COMMIT;

SELECT * FROM TB_DEPARTMENT;

CREATE TABLE TB_PROFESSOR(
    PROFESSOR_NO VARCHAR2(10) NOT NULL,
    PROFESSOR_NAME VARCHAR2(30) NOT NULL,
    PROFESSOR_SSN VARCHAR2(14) NULL,
    PROFESSOR_ADDRESS VARCHAR2(100) NULL,
    DEPARTMENT_NO VARCHAR2(10) NULL,
    PRIMARY KEY(PROFESSOR_NO), 
    FOREIGN KEY(DEPARTMENT_NO) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO)
);

COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NO IS '교수 번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_NAME IS '교수 이름';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_SSN IS '교수 주민번호';
COMMENT ON COLUMN TB_PROFESSOR.PROFESSOR_ADDRESS IS '교수 주소';
COMMENT ON COLUMN TB_PROFESSOR.DEPARTMENT_NO IS '학과 번호';

INSERT INTO TB_PROFESSOR 
VALUES('P002','양윤필','670510-1158493','서울시 광진구 하양동 111-12','001');
INSERT INTO TB_PROFESSOR 
VALUES('P034','박태환','600704-1138184','경기 안양시 만안구 석수1동 373-3백조(A)202동506','002');
INSERT INTO TB_PROFESSOR 
VALUES('P106','주영상','800707-1170344','부산시 남구 감만2동 국제A 101-1082','003');

CREATE TABLE TB_STUDENT(
    STUDENT_NO VARCHAR2(10) NOT NULL,
    DEPARTMENT_NO VARCHAR2(10) NOT NULL,
    STUDENT_NAME VARCHAR2(30) NOT NULL,
    STUDENT_SSN VARCHAR2(14) NULL,
    STUDENT_ADDRESS VARCHAR2(100) NULL,
    ENTRANCE_DATE DATE NULL,
    ABSENCE_YN CHAR(1) NULL,
    COACH_PROFESSOR_NO VARCHAR2(10) NULL,
    PRIMARY KEY(STUDENT_NO),
    FOREIGN KEY(DEPARTMENT_NO) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO),
    FOREIGN KEY(COACH_PROFESSOR_NO) REFERENCES TB_PROFESSOR(PROFESSOR_NO) ON DELETE SET NULL
);

COMMENT ON COLUMN TB_STUDENT.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.DEPARTMENT_NO IS '학과 번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STUDENT_SSN IS '학생 주민번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_ADDRESS IS '학생 주소';
COMMENT ON COLUMN TB_STUDENT.ENTRANCE_DATE IS '입학 일자';
COMMENT ON COLUMN TB_STUDENT.ABSENCE_YN IS '휴학 여부';
COMMENT ON COLUMN TB_STUDENT.COACH_PROFESSOR_NO IS '지도교수번호';

INSERT INTO TB_STUDENT
VALUES('9931111','001','박규상','800212-1161530','경기도 성남시 분당구 탑마을 526 경남아파트 710-1302',
        '99/03/01', 'N', 'P002');
        
INSERT INTO TB_STUDENT
VALUES('9931165','001','송근우','810125-1175561','경기도 부천시 원미구 중2동 386-1186 복사골 아파트 1701-405',
        '99/03/01', 'N', 'P106');
        
INSERT INTO TB_STUDENT
VALUES('9931190','003','오근우','790619-1165962','서울시 관안구 신림4동 513-1 3층',
        '99/03/01', 'N', 'P034');

--ORACLE--
SELECT 
S.STUDENT_NO, S.DEPARTMENT_NO, S.STUDENT_NAME, S.STUDENT_SSN, S.STUDENT_ADDRESS,
S.ENTRANCE_DATE, S.ABSENCE_YN, S.COACH_PROFESSOR_NO , D.DEPARTMENT_NAME, D.CATEGORY, 
D.OPEN_YN, D.CAPACITY, P.PROFESSOR_NAME, P.PROFESSOR_SSN, P.PROFESSOR_ADDRESS
FROM TB_STUDENT S , TB_DEPARTMENT D , TB_PROFESSOR P 
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO(+) AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO(+);

--ANSI--
SELECT 
S.STUDENT_NO, S.DEPARTMENT_NO, S.STUDENT_NAME, S.STUDENT_SSN, S.STUDENT_ADDRESS,
S.ENTRANCE_DATE, S.ABSENCE_YN, S.COACH_PROFESSOR_NO , D.DEPARTMENT_NAME, D.CATEGORY, 
D.OPEN_YN, D.CAPACITY, P.PROFESSOR_NAME, P.PROFESSOR_SSN, P.PROFESSOR_ADDRESS
FROM TB_STUDENT S LEFT JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO) 
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO);


CREATE TABLE TB_BOOKS(
    BOOK_ID NUMBER PRIMARY KEY,
    BOOKNAME VARCHAR2(50),
    BOOKPRICE NUMBER
);


4-1 
CREATE SEQUENCE SEQID 
START WITH 100
INCREMENT BY 1
MAXVALUE 999
NOCACHE
NOCYCLE;

SELECT SEQID.NEXTVAL FROM DUAL;

INSERT INTO TB_BOOKS(BOOK_ID,BOOKNAME,BOOKPRICE)
VALUES(SEQID.NEXTVAL, 'JAVA Programming', 30000);

SELECT * FROM TB_BOOKS;

DROP SEQUENCE SEQID;
DROP TABLE TB_BOOKS;